# Generated by Django 5.2 on 2025-04-20 12:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('search_url', models.URLField(max_length=1000)),
                ('search_keywords', models.CharField(help_text='Keywords used in the search', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_type', models.CharField(choices=[('5', 'Every 5 minutes'), ('15', 'Every 15 minutes'), ('30', 'Every 30 minutes'), ('60', 'Every hour'), ('180', 'Every 3 hours'), ('360', 'Every 6 hours'), ('1440', 'Daily'), ('custom', 'Custom')], default='60', help_text='How frequently to run this search', max_length=10)),
                ('frequency', models.IntegerField(default=60, help_text='Frequency in minutes to run this search')),
                ('custom_frequency', models.IntegerField(blank=True, help_text="Custom frequency in minutes (only used if schedule_type is 'custom')", null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('total_jobs_found', models.IntegerField(default=0)),
                ('total_notifications_sent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_searches', to='notifications.channels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Search Query',
                'verbose_name_plural': 'Job Search Queries',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='JobSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('jobs_found', models.IntegerField(default=0)),
                ('new_jobs_saved', models.IntegerField(default=0)),
                ('notifications_sent', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('running', 'Running')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jobs.jobsearchquery')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('price_type', models.CharField(choices=[('Hourly', 'Hourly'), ('Fixed Price', 'Fixed Price')], default='Hourly', max_length=50)),
                ('price_range', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('posted_date', models.CharField(max_length=50)),
                ('estimated_time', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('is_favorited', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('search_query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.jobsearchquery')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['url'], name='jobs_job_url_78379f_idx'), models.Index(fields=['user', 'created_at'], name='jobs_job_user_id_303f66_idx')],
                'unique_together': {('user', 'url')},
            },
        ),
    ]
