"""
Django settings for JobNotify project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from django.utils import timezone
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'huey.contrib.djhuey',
    'jobs',
    'notifications',
    "import_export",  # for db export import
    "admin_extra_buttons",  # for adding extra button
    "users",
    # django-allauth required apps
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
    'users.middleware.RedirectMiddleware'
]

# Add authentication backends
AUTHENTICATION_BACKENDS = [
    # Django default
    'django.contrib.auth.backends.ModelBackend',
    # django-allauth
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Site ID (required for django-allauth)
SITE_ID = 1

# Django-allauth settings
# AllAuth Settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGOUT_ON_GET = True  # Simple logout with a GET request
SOCIALACCOUNT_LOGIN_ON_GET = True  # Skip intermediate pages in OAuth flow
SOCIALACCOUNT_AUTO_SIGNUP = True  # Auto-create user accounts

# Use this if you want to skip the signup form when user has account created by social login
SOCIALACCOUNT_FORMS = {'signup': 'allauth.socialaccount.forms.DisconnectForm'}

# Only show Google as a login option
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# Login/logout URLs
LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/users/dashboard/'
LOGOUT_REDIRECT_URL = '/users/login/'

ROOT_URLCONF = 'JobNotify.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'JobNotify.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'

# The location where static files will be collected using `python manage.py collectstatic`
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional static directories (optional, if you have custom locations for static files)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Example: add static directories for your apps if needed
]

# WhiteNoise settings for compression and caching
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Basic Huey configuration with SQLite backend
HUEY = {
    'huey_class': 'huey.SqliteHuey',  # Use SQLite as the queue backend
    'filename': 'huey.sqlite',  # SQLite database file in project directory
    'name': 'upwork-job-tracker',  # Name of your app
    'results': True,  # Store task results
    'immediate': False,  # Run tasks asynchronously

    'consumer': {
        'workers': 2,  # Number of worker processes
        'worker_type': 'thread',  # Use threads instead of processes
        'periodic': True,  # Enable periodic tasks
    },
}

# Define the path for the logs directory
log_dir = os.path.join(BASE_DIR, 'logs')

# Check if the logs directory exists, if not, create it
if not os.path.exists(log_dir):
    os.makedirs(log_dir)

# Now you can safely configure the logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        # Main log file handler for Django
        'django_file': {
            'level': 'DEBUG',  # Log level (DEBUG, INFO, etc.)
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(log_dir, 'django.log'),  # Log file path
            'when': 'midnight',  # Rotate at midnight
            'backupCount': 180,  # Keep logs for 180 days (~6 months)
            'encoding': 'utf-8',
            'atTime': timezone.datetime.now(timezone.get_current_timezone()).replace(hour=0, minute=0, second=0,
                                                                                     microsecond=0),
        },
        # Task-specific log file handler
        'task_file': {
            'level': 'DEBUG',  # Log level (DEBUG, INFO, etc.)
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(log_dir, 'tasks.log'),  # Log file path
            'when': 'midnight',  # Rotate at midnight
            'backupCount': 90,  # Keep logs for 90 days (~3 months)
            'encoding': 'utf-8',
            'atTime': timezone.datetime.now(timezone.get_current_timezone()).replace(hour=0, minute=0, second=0,
                                                                                     microsecond=0),
        },
        # Scraper-specific log file handler
        'scraper_file': {
            'level': 'DEBUG',  # Log level (DEBUG, INFO, etc.)
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(log_dir, 'scraper.log'),  # Log file path
            'when': 'midnight',  # Rotate at midnight
            'backupCount': 90,  # Keep logs for 90 days (~3 months)
            'encoding': 'utf-8',
            'atTime': timezone.datetime.now(timezone.get_current_timezone()).replace(hour=0, minute=0, second=0,
                                                                                     microsecond=0),
        },
    },
    'loggers': {
        # Main logger for Django application
        'django': {
            'handlers': ['django_file'],
            'level': 'DEBUG',  # Log level (DEBUG, INFO, WARNING, etc.)
            'propagate': True,
        },
        # Logger for tasks
        'jobs.tasks': {
            'handlers': ['task_file'],
            'level': 'DEBUG',  # Log level (DEBUG, INFO, etc.)
            'propagate': False,  # Don't propagate to root logger
        },
        # Logger for scraper
        'jobs.scraper': {
            'handlers': ['scraper_file'],
            'level': 'DEBUG',  # Log level (DEBUG, INFO, etc.)
            'propagate': False,  # Don't propagate to root logger
        },
    },
}
