# Generated by Django 5.2 on 2025-04-20 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Channel Types',
            },
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('config', models.CharField(blank=True, help_text='Configuration URL for the notification service (e.g., Apprise URL)', max_length=255, null=True)),
                ('template', models.TextField(blank=True, help_text='Text/HTML template code for channel', null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False, help_text='If enabled, this channel can be used by all users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL)),
                ('channel_types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_types_ids', to='notifications.channeltypes')),
            ],
            options={
                'verbose_name_plural': 'Channels',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('extra', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('init', 'Init'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='init', max_length=6)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channels_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels_ids', to='notifications.channels')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
